version: "1.0"

services:
  bot:
    build: ./bot
    container_name: bot
    ports:
      - "8000:8000"
  mongodb:
    image: 'mongo:latest'
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
  server:
    depends_on:
      - mongodb
    build: ./server
    container_name: server
    ports:
      - "3000:3000"
  web:
    build: ./web
    container_name: web
    ports:
      - "5173:5173"

volumes:
  mongodb_data_container: