version: "3.2"

services:
  meu-monguinho:
    image: 'mongo:latest'
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

  redis:
    container_name: redis-cache
    image: redis:7.0-alpine
    ports:
      - 6379:6379
    volumes:
      - redis:/data

volumes:
  mongodb_data_container:
  redis:


networks:
  rabbitmq_go_net:
    driver: bridge
