version: "1.0"

services:
  mongodb:
    image: 'mongo:latest'
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
  server:
    depends_on:
      - mongodb
    build: .
    container_name: server
    ports:
      - "3000:3000"

volumes:
  mongodb_data_container:
  redis:

networks:
  rabbitmq_go_net:
    driver: bridge
